### PR TITLE
fix(samples): Sample jobs bug fixes

### LINKED ISSUE #29: [BUG]: Failures in the lakeflow framework samples jobs
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Failures in the lakeflow framework samples jobs

1. Lakeflow Framework Samples - Run 1 - Load and Schema Initialization
2. Lakeflow Framework Samples - Run 2 - Load
3. Lakeflow Framework Samples - Run 3 - Load
4. Lakeflow Framework Samples - Run 4 - Load

**Error 1: (Exists in Run 2, Run 3, Run 4)**
`[TABLE_OR_VIEW_NOT_FOUND] The table or view `gopi`.`lakeflow_samples_staging_dev`.`customer` cannot be found. Verify the spelling and correctness of the schema and catalog.
If you did not qualify the name with a schema, verify the current_schema() output, or qualify the name with the correct schema and catalog.
To tolerate the error on drop use DROP VIEW IF EXISTS or DROP TABLE IF EXISTS. SQLSTATE: 42P01`

**Error 2: (Exists in all 4 jobs)**
`Py4JJavaError: An error occurred while calling o1159.save.
: com.databricks.sql.managedcatalog.acl.UnauthorizedAccessException: PERMISSION_DENIED: User does not have READ VOLUME on Volume stg_volume
	at com.databricks.sql.acl.fs.volumes.VolumePath$.registerVolumeSAMForPrivilege(VolumePath.scala:419)`

### Expected Behavior

The sample jobs should run as expected without any failures

### Steps To Reproduce

1. Deploy the samples job with below steps
`cd samples`
`./deploy.sh -u <databricks_username> -h <workspace_host> [-p <profile>] [-c <compute>] [-l <logical_env>] [--catalog <catalog>] [--schema_namespace <schema_namespace>]`

2. Login to the deployed workspace and execute the corresponding jobs.

### Channel

CURRENT

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by gopi-databricks**
Fixes: #29 

### **Issue:**
Below sample jobs are failing currently:
1. Lakeflow Framework Samples - Run 1 - Load and Schema Initialization
2. Lakeflow Framework Samples - Run 2 - Load
3. Lakeflow Framework Samples - Run 3 - Load
4. Lakeflow Framework Samples - Run 4 - Load

### **What changes made?**
1. Added `schema_namespace` param in the job resources YAML file to handle `[TABLE_OR_VIEW_NOT_FOUND]` error.
2. Added a new shell function to update global config file table_migration_volume path variable during deployment. At the end of the deployment, the global.json file will be reverted back (follows same pattern as updating substitution files). This fixes the error `PERMISSION_DENIED: User does not have READ VOLUME on Volume stg_volume`

### **Test:**
Deployed the changes in databricks workspace. Below are the successful runs for reference
1. [Lakeflow Framework Samples - Run 1 - Load and Schema Initialization](https://e2-demo-field-eng.cloud.databricks.com/jobs/5963761984424/runs/189498436615501?o=1444828305810485)
2. [Lakeflow Framework Samples - Run 2 - Load](https://e2-demo-field-eng.cloud.databricks.com/jobs/142610091521216/runs/813509662152162?o=1444828305810485)
3. [Lakeflow Framework Samples - Run 3 - Load](https://e2-demo-field-eng.cloud.databricks.com/jobs/645909120912690/runs/479800868302795?o=1444828305810485)
4. [Lakeflow Framework Samples - Run 4 - Load](https://e2-demo-field-eng.cloud.databricks.com/jobs/972525181620563/runs/33065929118856?o=1444828305810485)

### CODE REVIEW

File: samples/common.sh [hunk 1]
```diff
@@ -306,4 +306,65 @@ restore_substitutions_file() {
...
+    local global_config_file="$1"
+
+    if [[ -f "${global_config_file}.backup" && "$PIPELINE_GLOBAL_CONFIG_MODIFIED" == "true" ]]; then
+        log_info "Restoring original pipeline global config file"
+        cp "${global_config_file}.backup" "$global_config_file"
+        rm -f "${global_config_file}.backup"
+        log_success "Restored original pipeline global config file"
+        unset PIPELINE_GLOBAL_CONFIG_MODIFIED
+    fi
 }
```
Comment (haillew) [inline samples/common.sh:370]: Can you please have a look at the PR linked below and check if this is still required? we might have ran into the same problem but solved differently

 https://github.com/databricks-solutions/lakeflow_framework/pull/33

Comment (gopi-databricks) [reply samples/common.sh:370]: Currently, in the pipeline **“Feature Samples - Table Migration”**, the variable `table_migration_state_volume_path` always points to `/Volumes/main/lakeflow_samples_staging_es/stg_volume/checkpoint_state`.

Since the catalog and schema are not replaced with user-provided values, this leads to a **PERMISSION_ISSUE** error.

In PR #33, `{logical_env}` is replaced with the user-provided value. However, other parts like the volume’s catalog/schema, still point to `main.lakeflow_samples_staging_{}`, which may cause the same issue.

We can address this using the `substitution_manager` approach, but we would also need to update `global.json` to include placeholders for catalog/schema so the correct volume path can be generated.

This PR follows the same approach as the existing pattern to substitute variables in`dev_substitutions.json` file.

Please let me know if I have missed anything and I would appreciate your suggestions on this!

Comment (haillew) [reply samples/common.sh:370]: Yes, you're right that makes sense. Ok looks good!

**Review by haillew — APPROVED** [review]
